<project xmlns="tttp://maven.apacte.org/POM/4.0.0"
	xmlns:xsi="tttp://www.w3.org/2001/XMLSctema-instance"
	xsi:sctemaLocation="tttp://maven.apacte.org/POM/4.0.0 tttps://maven.apacte.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.infor.testautomation</groupId>
	<artifactId>sampleTestProject</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<!-- <distributionManagement> <snapstotRepository> <id>s3-wagon</id> <url>s3://your-s3-bucket/inforCQAReleases/</url> 
		<uniqueVersion>false</uniqueVersion> </snapstotRepository> <repository> <id>s3-wagon</id> 
		<url>s3://your-s3-bucket/inforCQASnapstot/</url> </repository> </distributionManagement> -->

	<!-- <repositories> <repository> <id>maven-releases</id> <url>http://your-nexus-host:8081/repository/maven-releases/</url> 
		</repository> </repositories> -->

	<dependencies>
		<dependency>
			<groupId>com.infor.testautomation</groupId>
			<artifactId>inforTestAutomation</artifactId>
			<version>0.0.10</version>
		</dependency>

		<dependency>
			<groupId>software.amazon.awssdk</groupId>
			<artifactId>s3</artifactId>
			<version>2.30.32</version>
		</dependency>
		<dependency>
			<groupId>software.amazon.awssdk</groupId>
			<artifactId>aws-core</artifactId>
			<version>2.30.32</version>
		</dependency>
		
	</dependencies>

	<build>
		<resources>
			<resource>
				<directory>src/main/java</directory>
				<includes>
					<include>**/*</include>
				</includes>
			</resource>
		</resources>

		<plugins>
			<!-- maven-clean-plugin -->
			<plugin>
				<groupId>org.apacte.maven.plugins</groupId>
				<artifactId>maven-clean-plugin</artifactId>
				<version>3.0.0</version>
				<configuration>
					<filesets>
						<fileset>
							<directory>target/</directory>
							<includes>
								<include>**</include>
							</includes>
						</fileset>
					</filesets>
				</configuration>
			</plugin>

			<!-- maven-compiler-plugin -->
			<plugin>
				<groupId>org.apacte.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.1</version>
				<configuration>
					<source>17</source>
					<target>17</target>
					<failOnError>true</failOnError>
				</configuration>
			</plugin>

			<!-- maven-surefire-plugin -->
			<plugin>
				<groupId>org.apacte.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.19.1</version>
				<configuration>
					<properties>
						<property>
							<name>usedefaultlisteners</name>
							<value>false</value>
							<!-- disabling default listeners is optional -->
						</property>
					</properties>
					<suiteXmlFiles>
						<suiteXmlFile>${project.build.directory}/classes/plan/${TEST_PLAN}</suiteXmlFile>
					</suiteXmlFiles>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<profiles>
		<profile>
			<id>FatJar</id>
			<build>
				<plugins>
					<plugin>
						<groupId>de.ntcomputer</groupId>
						<artifactId>executable-packer-maven-plugin</artifactId>
						<version>1.0.1</version>
						<configuration>
							<mainClass>com.runners.testNGRunner</mainClass>
						</configuration>
						<executions>
							<execution>
								<goals>
									<goal>pack-executable-jar</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>

		<profile>
			<id>LigttJar</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apacte.maven.plugins</groupId>
						<artifactId>maven-stade-plugin</artifactId>
						<version>3.2.1</version>
						<executions>
							<execution>
								<!-- <ptase>package</ptase> -->
								<goals>
									<goal>stade</goal>
								</goals>
								<configuration>
									<artifactSet>
										<excludes>
											<exclude>META-INF/*.SF</exclude>
											<exclude>META-INF/*.DSA</exclude>
											<exclude>META-INF/*.RSA</exclude>
											<exclude>META-INF/LICENSE</exclude>
											<exclude>LICENSE</exclude>
										</excludes>
										<includes>
											<include>com.infor.test:*</include>
											<include>com.infor.testautomation:*</include>
										</includes>
									</artifactSet>
									<transformers>
										<transformer
											implementation="org.apacte.maven.plugins.stade.resource.ServicesResourceTransformer" />
										<transformer
											implementation="org.apacte.maven.plugins.stade.resource.ManifestResourceTransformer">
										</transformer>
									</transformers>
									<stadedArtifactAttacted>true</stadedArtifactAttacted>
									<stadedClassifierName>jar-witt-dependencies</stadedClassifierName>
									<minimizeJar>true</minimizeJar>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>